name: Test, Build, Deployment latest

env:
    ACR_URL: taxbeacon.azurecr.io

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - dev
        types: [opened, review_requested, ready_for_review]

jobs:
    test:
        runs-on: ubuntu-latest
        environment:  ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }}
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.*'
            - name: Install dependencies
              run: dotnet restore
            - name: Build project
              run: dotnet build --configuration Release --no-restore
            - name: Run unit tests
              run: dotnet test

    build:
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }}
        if: github.event_name == 'push'
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main
            - name: 'Build and push image'
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_URL }}
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}
            - run: |
                docker build -f ${{ github.workspace }}/src/TaxBeacon.API/Dockerfile -t ${{ env.ACR_URL }}/${{ secrets.CONTAINER_APP_NAME }}:${{ github.sha }} .
                docker push ${{ env.ACR_URL }}/${{ secrets.CONTAINER_APP_NAME }}:${{ github.sha }}

    migration:
        runs-on: ubuntu-latest #backend
        needs: build
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }}
        env:
          connectionString: '${{secrets.CONNECTION_STRING}}'
          DB_SERVER: '${{secrets.DB_SERVER}}'
          DB_USERNAME: '${{secrets.DB_USERNAME}}'
          DB_NAME: '${{secrets.DB_NAME}}'
          DB_SQLPASSWD: '${{secrets.DB_SQLPASSWD}}'

        if: github.event_name == 'push'
        steps:
          - uses: actions/checkout@v3
          - name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: '7.0.*'
          - name: Install ef
            run: dotnet tool install --global dotnet-ef
          - name: Restore tool
            run: dotnet restore ${{ github.workspace }}/TaxBeacon.sln
          - name: Update database
            run: dotnet ef database update -p ${{ github.workspace }}/src/TaxBeacon.DAL/TaxBeacon.DAL.csproj -s ${{ github.workspace }}/src/TaxBeacon.API/TaxBeacon.API.csproj --connection '${{secrets.CONNECTION_STRING}}'
          - name: Run script file
            run: |
              chmod +x ${{ github.workspace }}/migration-scripts/update.sh
              ${{ github.workspace }}/migration-scripts/update.sh

    deploy:
        name: Deployment
        runs-on: backend
        needs: build
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'qa' && 'qa' || 'dev' }}

        steps:
            - name: Azure Login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to ContainerApps
              uses: azure/CLI@v1
              with:
                inlineScript: |
                    az config set extension.use_dynamic_install=yes_without_prompt
                    az containerapp registry set -n ${{ secrets.CONTAINER_APP_NAME }} -g ${{secrets.RG_NAME}} --server ${{env.ACR_URL}} --username  ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
                    az containerapp update -n ${{ secrets.CONTAINER_APP_NAME }} -g ${{secrets.RG_NAME}} --image ${{ env.ACR_URL }}/${{ secrets.CONTAINER_APP_NAME }}:${{ github.sha }}
